name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: R0Wi/fork-sync@feature/auto-approve
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: R0Wi
          base: master
          head: master
          auto_approve: true
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
